- name: generate k8s.cfg for nagios
  template:
    src: nagios.cfg.j2
    dest: "/etc/nagios/servers/{{clusterName}}.cfg"
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['nagios']

- name: reloade nagios config
  ansible.builtin.shell:
    cmd: nagios -v /etc/nagios/nagios.cfg && service nagios reload
  when: inventory_hostname in groups['nagios']
