---
# handlers file for ansible-role-k8s/deploy-k8s-cluster
- name: nginx started
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: nginx reloaded 
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: haproxy started
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started

- name: haproxy reloaded 
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: kubelet restart
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: containerd restart 
  ansible.builtin.service:
    name: containerd
    state: restarted
