---
# handlers file for ansible-role-k8s/deploy-k8s-cluster
- name: haproxy started
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started

- name: haproxy reloaded 
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: kubelet restart
  ansible.builtin.service:
    name: kubelet
    enabled: yes
    state: restarted

- name: containerd restart 
  ansible.builtin.service:
    name: containerd
    enabled: yes
    state: restarted
